//
// Automatically generated make config: don't edit
// Chameleon Configuration
// Mon Dec  8 00:11:00 2014
// 
#define CONFIG_IS_BUILTIN   1
#define CONFIG_IS_MODULE    2
#define CONFIG_UCLIBCXX_MODULE CONFIG_IS_BUILTIN
#define CONFIG_SATA_MODULE CONFIG_IS_BUILTIN
#define CONFIG_KLIBC_MODULE CONFIG_IS_BUILTIN
#define CONFIG_OPENUP CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS CONFIG_IS_BUILTIN
#define CONFIG_ACPICODEC_MODULE CONFIG_IS_BUILTIN
#define CONFIG_OPTIMIZATION_LEVEL "-Oz"
#define CONFIG_KERNELPATCHER_MODULE CONFIG_IS_BUILTIN
#define CONFIG_BDMESG CONFIG_IS_BUILTIN
#define CONFIG_BOOT1INSTALL CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE CONFIG_IS_BUILTIN
#define CONFIG_FILENVRAM_MODULE CONFIG_IS_BUILTIN
#define CONFIG_FDISK440 CONFIG_IS_BUILTIN
#define CONFIG_RESOLUTION_MODULE CONFIG_IS_BUILTIN
#define CONFIG_KEYLAYOUT_MODULE CONFIG_IS_BUILTIN
