// Autogenerated - do not modify
#include <modules.h>
#include "boot_modules.h"
void start_built_in_modules() {
	start_built_in_module("klibc", "", "This module provides a standard c library for modules to link to if the library provided by chameleon is insufficient. This is currently only used by the uClibc++ library.", 0, 0, &klibc_start);
	start_built_in_module("uClibcxx", "", "This module provides a minimalistic c++ runtime library for use in other modules. This does not provide functionality by itself, instead it is used to allow for the c++ language to be used in other modules. Please note that rtti and exceptions has both been disabled. ", 0, 0, &uClibcxx_start);
	start_built_in_module("Resolution", "Chameleon", "This module reads the edid information from the monitor attached to the main display. The module will also patch the vesa modes available in pre intel hd graphics cards to provide proper resolution while booting.", 0, 0, &Resolution_start);
	start_built_in_module("Keylayout", "JrCs", "This module provides keylayout functionality", 0, 0, &Keylayout_start);
	start_built_in_module("Sata", "Cparm", "This module help Sata devices to be recognized as internal", 0, 0, &Sata_start);
	start_built_in_module("ACPICodec", "Cparm", "This module provides a remplacement for the internal acpi patcher", 0, 0, &ACPICodec_start);
}
}
